version: '2'

volumes:
  mongostorage:

services:

  mongodb:
      container_name: mongodb_container
      image: alexpunct/mongo:3.4
      volumes:
        - mongostorage:/data/db
      ports:
        - "27018:27017"
      command: mongod